### ISSUE TITLE
Analogies: error por falta de datos?

### ISSUE THREAD

**Issue by cerobpm** [cerobpm/analogia_y_persistencia#1]
ejecutando PronoEstac_Analogia.py:

Traceback (most recent call last):
  File "/home/alerta5/23-ANALOGIAS/PronoEstacional/PronoEstac_Analogia.py", line 190, in <module>
    df_prono_analog = MetodoAnalogia(nomEst,df_resamp,ObjSerie_i.var,mes_select,yr_select,vent_resamp,Param_Modelos)
  File "/home/alerta5/23-ANALOGIAS/PronoEstacional/Funciones/FuncSeasonalProno.py", line 358, in MetodoAnalogia
    R_Indic_i = Result_Indic[(Result_Indic['YrObs'] == yr_obj) & (Result_Indic['MesObs'] == mes_obj)]
TypeError: 'int' object is not subscriptable

**Comment by jbianchi81** [comment]
@guizzardi07 
Qué hacer ante falta de datos para buscar analogías? Opciones:
- cortar el proceso
- cortar la ejecución de esa CB y pasar a la siguiente

**Comment by jbianchi81** [comment]
branch [skip_CB_if_failed](https://github.com/cerobpm/analogia_y_persistencia/tree/skip_CB_if_failed)

**Comment by jbianchi81** [comment]
Solución: agrega serie de relleno (caso Pilco - Asunc)
branch https://github.com/cerobpm/analogia_y_persistencia/tree/serie_relleno

**Comment by jbianchi81** [comment]
Merged https://github.com/cerobpm/analogia_y_persistencia/commit/8fabc7edb03cf9309759bf19fdb673604409ab73
